services:

  product_producer:
    image: arthurescriou/product-producer:1.0.0
    platform: linux/amd64
    container_name: product_producer
    env_file: .env
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      STRAPI_URL: ${STRAPI_URL}
      STRAPI_TOKEN: ${STRAPI_TOKEN}
      FILE_NAME: /app/data/products.csv
    volumes:
      - ./data/products.csv:/app/data/products.csv
    networks:
      - "kafka"
    depends_on:
      - product_consumer

  product_consumer:
    platform: linux/amd64
    image: arthurescriou/product-consumer:1.0.3
    container_name: product_consumer
    env_file: .env
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      STRAPI_URL: ${STRAPI_URL}
      STRAPI_TOKEN: ${STRAPI_TOKEN}
    networks:
      - "kafka"
      - "strapi"

  event_producer:
    platform: linux/amd64
    image: arthurescriou/event-producer:1.0.3
    container_name: event_producer
    env_file: .env
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      STRAPI_URL: ${STRAPI_URL}
      STRAPI_TOKEN: ${STRAPI_TOKEN} 
      FILE_NAME: /app/data/events.csv   
    volumes:
      - ./data/events.csv:/app/data/events.csv  
    networks:
      - "kafka"
    depends_on:
        - event_consumer

  event_consumer:
    platform: linux/amd64
    image: arthurescriou/event-consumer:1.0.0
    container_name: event_consumer
    env_file: .env
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      STRAPI_URL: ${STRAPI_URL}
      STRAPI_TOKEN: ${STRAPI_TOKEN}
    networks:
      - "strapi"
      - "kafka"

  stock_producer:
    platform: linux/amd64
    image: arthurescriou/stock-producer:1.0.0
    container_name: stock_producer
    env_file: .env
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      STRAPI_URL: ${STRAPI_URL}
      STRAPI_TOKEN: ${STRAPI_TOKEN}
      FILE_NAME: stocks.csv
    volumes:
      - ./data/stocks.csv:/stocks.csv
    networks:
      - "kafka"
    depends_on:
      - stock_consumer

  stock_consumer:
    platform: linux/amd64
    image: stock_consumer
    container_name: stock_consumer
    env_file: .env
    environment:
      BROKER_1: kafka:9092
      BROKER_2: kafka:9092
      BROKER_3: kafka:9092
      STRAPI_URL: ${STRAPI_URL}
      STRAPI_TOKEN: ${STRAPI_TOKEN}
    networks:
      - "strapi"
      - "kafka"

networks:
  strapi:
    external: true
    name: final_strapi
  kafka:
    external: true
    name: final_kafka